site_name: EthHub
site_description: Essential source for Ethereum information.
theme:
  name: 'material'
  custom_dir: 'docs/material'
  palette:
    primary: 'ethhub'
  logo: 'logo.png'
  favicon: 'assets/images/favicon.ico'
  feature:
    tabs: true

extra_css: [extra.css]
markdown_extensions:
  - meta

repo_name: 'ethhub-io/ethhub-zh'
repo_url: 'https://github.com/ethhub-io/ethhub-zh'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/ethhub-io/ethhub'
    - type: 'twitter'
      link: 'https://twitter.com/ethhub_io'
    - type: 'medium'
      link: 'https://medium.com/ethhub'
    - type: 'comment'
      link: 'https://discordapp.com/invite/gw8AM98'
    - type: 'instagram'
      link: 'https://www.instagram.com/ethhub_io/'

google_analytics:
  - 'UA-125892125-2'
  - 'auto'

nav:
- Home: 'index.md'
- Docs: 'ethereum-basics/what-is-ethereum.md'
- Podcast: 'https://podcast.ethhub.io'
- Newsletter: 'https://ethhub.substack.com/'
- Shop: 'https://shop.ethhub.io'
